### ISSUE TITLE
"-p" option for pausing neural network won't work

### ISSUE THREAD

**Issue by MaDooSan** [davidrmiller/neural2d#28]
I found out that the "-p" option does not work for me anymore in the latest release of neural2d. The program still continues to run the training routine. It works perfectly in the older release. Am I doing something wrong?

P.S: I'm running neural2d on Ubuntu.

Thanks in advance!

**Comment by davidrmiller** [comment]
@MaDooSan, the source code hasn't changed in over a year, so nothing comes to mind immediately. Feel free to give us more details on how you obtained the source code, compiled it, what compiler and OS version, how you're running the program, etc.

**Comment by MaDooSan** [comment]
@davidrmiller, that's what I thought too. I must be missing something, and I'm hoping you can help me see what that is. I'm using Ubuntu 14.04. I followed the instructions on the documentation to create a /build/ folder in the cloned repository and compiled the library using cmake.
Everything works fine, except when I use the "-p" option, like shown:
./neural2d topology.txt inputData.txt weights.txt -p 
It seems that setting the net's 'isRunning' status to false doesn't pause it.
As I mentioned previously, when I tried the same thing on your first release, it worked as expected, i.e. the program pauses and I can open a browser that has the GUI.

**Comment by davidrmiller** [comment]
Ubuntu 14.04 should work. Here are some ideas: Double-check the Makefile and make sure there is no compiler flag like "-DDISABLE_WEBSERVER". Also check neural2d.h and make sure that line 92 contains "#define ENABLE_WEBSERVER". If that's not it, could it be a difference in our compiler versions? Or cmake versions? If necessary, you could also check out older versions of neural2d and determine if there's a particular code check-in that broke this feature for you.

**Comment by MaDooSan** [comment]
@davidrmiller, thank you for the suggestions. I will test them out.
Cheers!

**Comment by davidrmiller** [comment]
I just tested a fresh clone of the repository with Ubuntu 14.04, and you are right -- by default the optional webserver is not compiled and linked, and the instructions in the README are not clear how to enable it. 

To compile and link the webserver, run cmake with the option "-DWEBSERVER=ON", and then rebuild the neural2d executable. For example:
```
cd build
cmake -DWEBSERVER=ON ..
make
```
I'll update the README later with clearer information.

At some point we must have changed the default, and that's when the webserver stopped working for you. To change the default so that the webserver gets compiled without having to supply a cmake parameter, see around line 19 in CMakeLists.txt in the top level directory.

Thanks for submitting this issue!

**Comment by MaDooSan** [comment]
Thanks a million, it works beautifully!
Glad to help :)
